<hr />
<table style="width:100%; border-collapse: collapse;">
<tr>
<td>
<span>Copyright 2025, Andrew McGinnis.</span>
</td>
<td>
<a href="https://jigsaw.w3.org/css-validator/check/referer" style="float: right">
<img style="border:0;width:88px;height:31px"
src="https://jigsaw.w3.org/css-validator/images/vcss" alt="Valid CSS!" />
</a>
<a href="https://validator.w3.org/check?uri=referer" style="float: right">
<img src="https://www.w3.org/Icons/valid-xhtml10" alt="Valid XHTML 1.0 Strict" 
height="31" width="88" /></a>
</td>
</tr>
</table>
