<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
<link rel="stylesheet" href="style.css"/>
<title>TITLE</title>
<meta name="color-scheme" content="dark light"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
</head>
<body>
<div class="header">
#include "navbar.phtml"
<hr />
</div>
