#define TITLE Home - McGinnis.space
#include "header.phtml"
<h1>Welcome</h1>
<p>Welcome to my web site. Although this site is currently under
construction, I hope you find something here of interest to you.
In particular, I expect my links page to be popular. Set it as your
browser's homepage for easy access to all the useful pages you'd be
typing in anyway, as soon as you start your browser or open a new tab.
</p>
</body>
</html>
