#include "header.phtml"
#define TITLE Links Page
<form action="https://duckduckgo.com/" method="get" style="text-align:center">
<table style="width:100%">
<tbody><tr>
<td style="width:7em"><label for="q">Web Search:</label></td>
<td><input type="text" id="q" name="q" style="width:100%"></td>
<td style="width:1px">
<!--extra cell to prevent overflow and keep button text centered in Safari-->
</td>
<td style="width:3em">
<input type="submit" value="Go" style="width:100%">
</td>
</tr>
</tbody></table>
</form>
<br>
<div class="columns">
<a href="https://forecast.weather.gov/MapClick.php?textField1=43.05&amp;textField2=-76.15">NWS Syracuse Weather Forecast</a>
<p><a href="https://weather.gc.ca/index_e.html">Environment Canada Weather Page</a></p>
<p><a href="https://coastwatch.glerl.noaa.gov/contour/region_map.html">Great Lakes Surface Temperature</a></p>
<p><a href="https://www2.nysmesonet.org/">New York State Mesonet</a></p>
<p><a href="https://www.ospo.noaa.gov/Products/ocean/sst.html">NOAA Sea Surface Temperature Charts</a></p>
<p><a href="https://www.nohrsc.noaa.gov/interactive/html/map.html">Snow Accumulation Maps</a></p>
<p><a href="https://intranet.clarkson.edu/">Clarkson Intranet</a></p>
<p><a href="https://www.visionsfcu.org/">Visions FCU Online Banking</a></p>
<p><a href="https://investor.vanguard.com/">Vanguard Brokerage</a></p>
<div style="break-inside: avoid-column; page-break-inside: avoid;">
<b>Syracuse Post Standard</b>
<ul>
<li><a href="https://reader.ps.syracuse.com/">Print Edition</a></li>
<li><a href="https://www.syracuse.com/">Online Edition</a></li>
</ul>
</div>
<p><a href="http://finance.yahoo.com/">Yahoo Finance</a></p>
<p><a href="https://fred.stlouisfed.org/">FRED Federal Reserve Economic Data</a></p>
<p><a href="https://511ny.org/map#:Alerts">New York State 511</a></p>
<p><a href="https://ocrra.org/how-do-i-get-rid-of/">OCRRA How Do I Get Rid Of</a></p>
<p><a href="https://outagemap.ny.nationalgridus.com/">National Grid Outage Map</a></p>
<p><a href="https://www.nyiso.com/real-time-dashboard">NYISO Real Time Dashboard</a></p>
<p><a href="https://www.onlib.org/">Onondaga County Library</a></p>
<p><a href="https://archive.org/">Internet Archive</a></p>
<p><a href="http://engineeringtoolbox.com/">Engineering Toolbox</a></p>
</div>
<hr>
<small>Make this your browser's home page!</small>
</body></html>
